import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

const doc = new PDFDocument();
const outputPath = 'C:\\Users\\kali_\\OneDrive\\Desktop\\Mern\\Mern-Financial-Trading-Dashboard\\Data_Architecture_Explained.pdf';

doc.pipe(fs.createWriteStream(outputPath));

doc.fontSize(20).text('Data Architecture: Where Does The Data Come From?', { align: 'center' });
doc.moveDown();

doc.fontSize(12).text('Your dashboard is a clever mix of manually added static data, real-time live market data, and dynamic mathematical calculations. Here is the exact lifecycle of your data:', { align: 'justify' });
doc.moveDown();

doc.fontSize(16).text('1. The Core Asset Information (Static / Database)');
doc.fontSize(12).text(`When you look at the Assets Page or the dropdown menu to select an asset to buy, you see names like "Apple Inc.", "Microsoft Corporation", and "Bitcoin".
- Where it comes from: This data is stored in your MongoDB database inside the 'assets' collection.
- How it got there: It was initially manually added or "seeded" into your database by the developer. The database holds static details like the symbol (AAPL), the company name (Apple Inc.), the sector (Technology), and the logo. This part does not change on its own.`);
doc.moveDown();

doc.fontSize(16).text('2. The Live Prices & Live Feed (100% Live Dynamic Data)');
doc.fontSize(12).text(`When you look at the Live Market Feed or the Current Price of an asset, the numbers are constantly blinking and changing.
- Where it comes from: This comes directly from the Finnhub Market Data API that we just integrated.
- How it works:
  1. Your Node.js backend connects to Finnhub using a real-time connection called a WebSocket.
  2. The backend looks at your static database and says, "Hey Finnhub, I have AAPL, MSFT, and BTC in my database. Send me their prices."
  3. Every time someone in the real world trades an Apple stock, Finnhub instantly sends a tiny message to your backend: {"symbol": "AAPL", "price": 212.63}.
  4. Your backend immediately updates the currentPrice in your MongoDB database to $212.63.
  5. Your backend instantly shouts that new price to your React frontend using Socket.io. Your screen updates without you ever having to hit refresh.`);
doc.moveDown();

doc.fontSize(16).text('3. Your Portfolio, Net Worth, & P/L (Dynamic Mathematical Data)');
doc.fontSize(12).text(`When you look at your Trading Dashboard and see "Portfolio Value: $5,630.30" or "Unrealized P/L: $1,472.37".
- Where it comes from: This data is dynamically calculated by your backend every time the page loads or a price changes. It is not static, and it is not coming directly from an external API.
- How it works:
  1. Let's say you placed a trade yesterday to buy 5 shares of Apple at $200 each. That action was saved statically in your MongoDB trades collection as your personal trade history.
  2. Today, your backend asks: "How much is this user's portfolio worth right now?"
  3. The backend grabs your 5 shares from the database.
  4. It grabs the live Apple price from Finnhub (let's say it's $212).
  5. It multiplies 5 shares x $212 = $1,060.
  6. It calculates your profit: $1,060 (current value) - $1,000 (what you paid) = $60 Profit.
  7. It does this math for every single stock you own and adds them all together to show you your total Net Worth and total P/L on the screen.`);
doc.moveDown();

doc.fontSize(16).text('4. The Charts (Historical Dynamic Data)');
doc.fontSize(12).text(`When you see the curved lines on the "Portfolio Growth" chart.
- Where it comes from: This is generated by looking at your portfolio's value over time.
- How it works: Whenever a live price updates, or whenever you make a trade, the system recalculates your total portfolio value. By taking snapshots of your total value over days, weeks, or months, the frontend charting library connects those dots to draw the line you see.`);
doc.moveDown();

doc.fontSize(14).text('Summary');
doc.fontSize(12).text(`- Names & Symbols (AAPL): Static data sitting in your database.
- The Prices ($212.63): Live, real-world dynamic data streaming in every second from Finnhub.
- Your Money & Profits ($5,630.30): Dynamic math calculated by your own backend, combining your personal trade history with the live prices!`);

doc.end();
console.log('PDF generated successfully');
